micronaut:
  application:
    name: toyapp

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${DATABASE_URL:`jdbc:postgresql://localhost:5432/toyapp`}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      schemas: toyapp
      default-schema: toyapp

datasources:
  default:
    url: ${DATABASE_URL:`jdbc:postgresql://localhost:5432/toyapp`}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

jpa:
  default:
    packages-to-scan:
      - "com.learning.data"
    properties:
      hibernate:
        show_sql: false
