version: '3.8'

services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: toyapp
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    volumes:
      - ./.data:/var/lib/postgresql/data
